on:
  push:
    branches-ignore:
    - 'master'
    tags-ignore:
    - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Lint
        uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Tests
        run: go test ./... -race -parallel 2 -shuffle on -v
        env:
          CGO_ENABLED: 1
